= HTTPS Development setup
:toc: right
:toclevels: 5

[[certificates]]
== Certificates
We will use the [step](https://smallstep.com/docs/step-cli) tool for the cer generation.

**Installation**
Download latest the `rpm` from the [GitHub](https://github.com/smallstep/cli/releases)
[source, bash]
....
sudo dnf install -y ./step-cli_*.rpm
....

**Create a Root CA**
[source, bash]
....
step certificate create --no-password --insecure --profile root-ca "Foreman Devel Root CA" root_ca.crt root_ca.key
....

Create certificates
[source, bash]
....
step certificate create foreman.example.com foreman.example.com.crt foreman.example.com.key \
    --profile leaf --not-after=8760h \
    --ca ./intermediate_ca.crt --ca-key ./intermediate_ca.key --bundle \
    --no-password --insecure
....

Install the certificate into the system trust store
[source, bash]
....
step certificate install root_ca.crt
....

[[apache]]
== Apache configuration

Enable listening on `443` port in `conf/httpd.conf`
[source, bash]
....
Listen 443
....

Create config file for the Foreman
[source, text]
....
# /etc/httpd/conf.d/foreman.example.com.conf

<VirtualHost *:80>
  ServerName foreman.example.com

  ProxyPass / http://127.0.0.1:3000/
  ProxyPassReverse / http://127.0.0.1:3000/

  RequestHeader set X-Forwarded-Proto http
</VirtualHost>

<VirtualHost *:443>
  ServerName foreman.example.com

  SSLEngine on
  SSLCertificateFile /path/to/certs-folder/example.com.crt
  SSLCertificateKeyFile /path/to/certs-folder/example.com.key

  SSLOptions +ExportCertData

  RequestHeader set X-Forwarded-Proto https

  RequestHeader set SSL_CLIENT_S_DN "%{SSL_CLIENT_S_DN}s"
  RequestHeader set SSL_CLIENT_CERT "%{SSL_CLIENT_CERT}s"
  RequestHeader set SSL_CLIENT_VERIFY "%{SSL_CLIENT_VERIFY}s"

  <Location "/">
    ProxyPass http://localhost:3000/
    ProxyPassReverse http://localhost:3000/
  </Location>
</VirtualHost>
....

Apply changes
[source, bash]
....
apachectl configtest
service httpd restart
....

[[foreman]]
== Foreman

[[running-foreman]]
=== Running Foreman

Backend:
[source, bash]
....
bundle exec rails server --binding 0.0.0.0 --port 3000
....

Frontend
[source, bash]
....
# Webpack
./node_modules/.bin/webpack-dev-server-without-h2 --config ./config/webpack.config.js \
  --allowed-hosts foreman.example.com \
  --https \
  --cert '/path/to/certs-folder/foreman.example.com.crt' \
  --key '/path/to/certs-folder/foreman.example.com.key'
....

[[configuring-foreman]]
=== Configuring Foreman
## Foreman configuration
`config/settings.yaml`
[source, yaml]
....
# :require_ssl: true (TODO: verify provisioning, templates, ansible, remote_execution)
:webpack_dev_server_https: true
....

Update settings:
* `SSL certificate`: `/path/to/certs-folder/foreman.example.com.crt`
* `SSL CA file`: `/path/to/certs-folder/rootCA.crt`
* `SSL private key`: `/path/to/certs-folder/foreman.example.com.key`
* `SSL client DN env`: `HTTP_SSL_CLIENT_S_DN`
* `SSL client verify env`: `HTTP_SSL_CLIENT_VERIFY`
* `SSL client cert env`: `HTTP_SSL_CLIENT_CERT`

[[smart-proxy]]
== Smart Proxy
`config/settings.yml`
[source, yaml]
....
:foreman_url: https://foreman.example.com
:http_port: 8080
:https_port: 8443
:ssl_certificate: /path/to/certs-folder/foreman.example.com.crt
:ssl_ca_file: /path/to/certs-folder/rootCA.crt
:ssl_private_key: /path/to/certs-folder/foreman.example.com.key
....

[[proxy-modules]]
=== Modules
**Registration**
[source, yaml]
....
---
:enabled: true
:registration_url: "https://foreman.example.com:8443"
....

(TODO:) **Dynflow (Remote execution)**
[source, yaml]
....
....

(TODO:) **Ansible**
[source, yaml]
....
....

(TODO:) **Templates**
[source, yaml]
....
....
